const ACCESS_TOKEN_COOKIE_NAME = 'access';
const REFRESH_TOKEN_COOKIE_NAME = 'refresh';
const CSRF_TOKEN_COOKIE_NAME = 'csrf';
const CSRF_HEADER = 'X-CSRF-Token';

export { ACCESS_TOKEN_COOKIE_NAME, REFRESH_TOKEN_COOKIE_NAME, CSRF_TOKEN_COOKIE_NAME, CSRF_HEADER };
