openapi: 3.0.1
info:
  title: Mars API
  description: >
    MARS (Music ARchival Software) is an archival service that aggregates your most listened
    to songs on a weekly and monthly basis and allows you to view and download the songs.
  contact:
    name: Matthew DeGuzman
    url: https://github.com/matt-dz/mars

servers:
  - url: http://127.0.0.1:8080
    description: Development server

security:
  - BearerTokenAuth: []

tags:
  - name: Health
    description: Health check endpoints
  - name: Auth
    description: Endpoints for logging in and managing auth sessions
  - name: OAuth
    description: Endpoints for managing OAuth2.0 sessions

paths:
  /api/openapi.yaml:
    get:
      summary: Get OpenAPI specification.
      security: []
      tags:
        - Documentation
      responses:
        "200":
          description: OpenAPI specification file
          content:
            application/x-yaml:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/health:
    get:
      tags:
        - Health
      summary: Health check
      description: Returns the health status of the API
      security: []
      responses:
        "204":
          description: API is healthy
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/login:
    post:
      tags:
        - Auth
      summary: User login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: >
            OK - For browser clients, access and refresh tokens are set as HTTP-only
            cookies. For API clients/Swagger, an access token is also returned in the body.
          headers:
            Set-Cookie:
              description: >
                HTTP-only cookies for access and refresh tokens. This header is sent thrice:
                once for the "access" cookie, once for the "refresh" cookie, and once for the "csrf" cookie.
              schema:
                type: string
              examples:
                access:
                  summary: Access token cookie
                  value: access=<jwt_token>; HttpOnly; Secure; SameSite=Lax; Path=/
                refresh:
                  summary: Refresh token cookie
                  value: refresh=<jwt_token>; HttpOnly; Secure; SameSite=Lax; Path=/
                csrf:
                  summary: CSRF token cookie
                  value: csrf=<csrf_token>; Secure; SameSite=Lax; Path=/
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Incorrect email or password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/auth/refresh:
    post:
      summary: Refresh session tokens
      tags:
        - Auth
      description: >
        Uses a valid refresh token cookie to issue a new access and refresh token pair.
      security: []
      parameters:
        - $ref: "#/components/parameters/RefreshTokenCookie"
        - $ref: "#/components/parameters/CsrfTokenHeader"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshToken"
      responses:
        "200":
          description: >
            OK - For browser clients, access and refresh tokens are set as HTTP-only
            cookies. For API clients/Swagger, an access token is also returned in the body.
          headers:
            Set-Cookie:
              description: >
                HTTP-only cookies for access and refresh tokens. This header is sent twice:
                once for the "access" cookie and once for the "refresh" cookie.
              schema:
                type: string
              examples:
                access:
                  summary: Access token cookie
                  value: access=<jwt_token>; HttpOnly; Secure; SameSite=Lax; Path=/
                refresh:
                  summary: Refresh token cookie
                  value: refresh=<jwt_token>; HttpOnly; Secure; SameSite=Lax; Path=/
                csrf:
                  summary: CSRF token cookie
                  value: csrf=<csrf_token>; Secure; SameSite=Lax; Path=/
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Expired, invalid, or missing refresh token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/auth/verify:
    get:
      summary: Verify user session
      tags:
        - Auth
      description: >
        Validates the user's access token cookie, checks expiration,
        and ensures the user has the required role.
      parameters:
        - name: access
          in: cookie
          schema:
            type: string
          description: Access token
        - name: role
          in: query
          schema:
            $ref: "#/components/schemas/Role"
      responses:
        "204":
          description: Session is valid
        "401":
          description: Expired, invalid, or missing access token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Insufficient permissions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/oauth/spotify/token:
    post:
      summary: Get Spotify OAuth2.0 tokens.
      tags:
        - OAuth
      description: >
        Exchange an authorization code for Spotify OAuth2.0 tokens.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpotifyTokenRequest"
      responses:
        "204":
          description: Successfully exchanged tokens
        "400":
          description: Bad Request - Invalid Code
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/spotify/status:
    get:
      summary: Get Spotify OAuth2.0 status.
      tags:
        - OAuth
      description: >
        Gets the integration status of a user's Spotify connection
        by checking if their access token exists/is still valid.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpotifyStatusResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  parameters:
    CsrfTokenHeader:
      name: X-CSRF-Token
      in: header
      required: false
      description: >
        CSRF token required when authenticating via cookies.
        Must match the CSRF cookie value.
      schema:
        type: string

    RefreshTokenCookie:
      name: refresh
      in: cookie
      schema:
        type: string
      description: Refresh token

  schemas:
    SpotifyStatusResponse:
      type: object
      properties:
        connected:
          type: boolean
      required:
        - connected

    SpotifyTokenRequest:
      type: object
      properties:
        code:
          type: string
      required:
        - code

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
          description: >
            JWT access token to use in the Authorization: Bearer header.
        token_type:
          type: string
          example: Bearer
        expires_in:
          type: integer
          format: int64
          description: Access token lifetime in seconds.
      required:
        - access_token
        - token_type
        - expires_in

    Error:
      type: object
      properties:
        code:
          type: string
        error_id:
          type: integer
          format: uint64
        message:
          type: string
        status:
          type: integer
      required:
        - code
        - error_id
        - message
        - status
      example:
        code: track_not_found
        error_id: "12345678"
        message: track does not exist
        status: 404

    RefreshToken:
      type: object
      properties:
        refresh_token:
          type: string
          description: Refresh token

    Role:
      type: string
      enum:
        - user
        - admin

  securitySchemes:
    BearerTokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
