// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Playlist struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PlaylistType interface{}
	Name         string
	Timestamp    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type PlaylistTrack struct {
	PlaylistID uuid.UUID
	TrackID    string
	Plays      int32
}

type SpotifyToken struct {
	SpotifyUserID string
	AccessToken   string
	TokenType     string
	Scope         string
	RefreshToken  string
	TokenExpires  pgtype.Timestamptz
}

type Track struct {
	ID        string
	Name      string
	Artists   []string
	Href      string
	ImageUrl  pgtype.Text
	Raw       []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TrackListen struct {
	UserID   uuid.UUID
	TrackID  string
	PlayedAt pgtype.Timestamptz
}

type User struct {
	ID                    uuid.UUID
	Email                 string
	Role                  interface{}
	PasswordHash          string
	SpotifyID             pgtype.Text
	RefreshTokenHash      pgtype.Text
	RefreshTokenExpiresAt pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}
