// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PlaylistType string

const (
	PlaylistTypeWeekly  PlaylistType = "weekly"
	PlaylistTypeMonthly PlaylistType = "monthly"
)

func (e *PlaylistType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlaylistType(s)
	case string:
		*e = PlaylistType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlaylistType: %T", src)
	}
	return nil
}

type NullPlaylistType struct {
	PlaylistType PlaylistType
	Valid        bool // Valid is true if PlaylistType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlaylistType) Scan(value interface{}) error {
	if value == nil {
		ns.PlaylistType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlaylistType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlaylistType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlaylistType), nil
}

type Role string

const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Playlist struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PlaylistType PlaylistType
	Name         string
	Timestamp    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type PlaylistTrack struct {
	PlaylistID uuid.UUID
	TrackID    string
	Plays      int32
}

type SpotifyToken struct {
	SpotifyUserID string
	AccessToken   string
	TokenType     string
	Scope         string
	RefreshToken  string
	ExpiresAt     pgtype.Timestamptz
}

type Track struct {
	ID        string
	Name      string
	Artists   []string
	Href      string
	ImageUrl  pgtype.Text
	Raw       []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TrackListen struct {
	UserID   uuid.UUID
	TrackID  string
	PlayedAt pgtype.Timestamptz
}

type User struct {
	ID                    uuid.UUID
	Email                 string
	Role                  Role
	PasswordHash          string
	SpotifyID             pgtype.Text
	RefreshTokenHash      pgtype.Text
	RefreshTokenExpiresAt pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}
