// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
)

type Querier interface {
	CheckUsersTableExists(ctx context.Context) (bool, error)
}

var _ Querier = (*Queries)(nil)
